esphome:
  name: hub75-matrix
  friendly_name: HUB75 Matrix Display

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "Cogito Ergo Sum"
  password: "bart-LETICIA-kyra"
  
  
api:
 
ota:
  platform: esphome
  
logger:
  level: INFO

# HUB75 configuratie
display:
  - platform: hub75
    id: matrix_display
    panel_width: 256
    panel_height: 128
    update_interval: 50ms  # Langzamer = minder geheugen intensief
    
    # Pin configuratie (test dit, kan per display variant verschillen)
    r1_pin: GPIO25
    g1_pin: GPIO26
    b1_pin: GPIO27
    r2_pin: GPIO14
    g2_pin: GPIO12
    b2_pin: GPIO13
    
    a_pin: GPIO23
    b_pin: GPIO22
    c_pin: GPIO5
    d_pin: GPIO17
    e_pin: GPIO18  # Voor 1/32 scan
    
    clk_pin: GPIO16
    lat_pin: GPIO4
    oe_pin: GPIO15
    
    brightness: 50  # Start laag (0-255), verhoog indien nodig
    
    lambda: |-
      it.strftime(10, 10, id(font_medium), "%H:%M", id(homeassistant_time).now());
      it.print(10, 40, id(font_small), "Home Assistant");

# Fonts - houd deze klein om geheugen te besparen
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 16
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"
    
  - file: "gfonts://Roboto@700"
    id: font_medium
    size: 24
    glyphs: ":0123456789"

# Tijd synchronisatie
time:
  - platform: homeassistant
    id: homeassistant_time

# Voorbeeld: tekst vanuit Home Assistant
text_sensor:
  - platform: homeassistant
    id: display_message
    entity_id: input_text.matrix_display_text
    on_value:
      then:
        - component.update: matrix_display

# Voorbeeld: sensor data
sensor:
  - platform: homeassistant
    id: temp_buiten
    entity_id: sensor.buitentemperatuur