esphome:
  name: hub75-matrix
  friendly_name: HUB75 Matrix Display

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "Cogito Ergo Sum"
  password: "bart-LETICIA-kyra"
  
  
api:
 
ota:
  platform: esphome

logger:
  level: INFO

# HUB75 configuratie
display:
  - platform: hub75
    id: matrix
    panel_width: 64          # test kleiner!
    panel_height: 32
    update_interval: 20ms
    brightness: 80           # 0-255

    # RGB-data
    r1_pin: GPIO25
    g1_pin: GPIO26
    b1_pin: GPIO27
    r2_pin: GPIO14
    g2_pin: GPIO12
    b2_pin: GPIO13

    # Row-select
    a_pin: GPIO23
    b_pin: GPIO22
    c_pin: GPIO5
    d_pin: GPIO17            # we testen 1/16-scan
    # e_pin: GPIO18          # alleen bij 1/32-scan

    # Control
    clk_pin: GPIO16
    lat_pin: GPIO4
    oe_pin: GPIO15

    lambda: |-
      it.fill(Color(0, 0, 128));   // blauw vlak → bewijs dat pinnen & voeding OK zijn

# Fonts - houd deze klein om geheugen te besparen
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 16
    glyphs: "!\"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"
    
  - file: "gfonts://Roboto@700"
    id: font_medium
    size: 24
    glyphs: ":0123456789"

# Tijd synchronisatie
time:
  - platform: homeassistant
    id: homeassistant_time

# Voorbeeld: tekst vanuit Home Assistant
text_sensor:
  - platform: homeassistant
    id: display_message
    entity_id: input_text.matrix_display_text
    on_value:
      then:
        - component.update: matrix

# Voorbeeld: sensor data
sensor:
  - platform: homeassistant
    id: temp_buiten
    entity_id: sensor.buitentemperatuur