esphome:
  name: matrix
  friendly_name: matrix

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "haz9QTgDtZjC/v56dYkIumRli+xGyQjLQfrbyGIV+AA="

ota:
  - platform: esphome
    password: "fc2aa4f46d502bf3563a1af4e8fc5673"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Matrix Fallback Hotspot"
    password: "WnrdYanrbN33"

captive_portal:


light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO21
    num_leds: 64
    chipset: ws2812
    name: "WS2812 Matrix"
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    