esphome:
  name: led
  friendly_name: led

  

esp8266:
  board: esp01_1m

# Example configuration entry
# Example configuration entry
light:
  - platform: status_led
    name: "status green"
    pin: GPIO13

  - platform: status_led
    name: "status orange"
    pin: GPIO15

  - platform: status_led
    name: "status red"
    pin: GPIO16
          


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "L+dKU3zMjr13L2Z673rvXPj/iyM/0Nv9DfSn66ouyGI="

ota:
  - platform: esphome
    password: "e0fb44a1c200d53a9932062dba464d0e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Fallback Hotspot"
    password: "KU6cLwCWrap9"

captive_portal:
    