esphome:
  name: touch
  friendly_name: touch

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0q8W7CxkIOHk8Vl4ymKOj2eBml8tmuHUvZkwLKEUg98="

ota:
  - platform: esphome
    password: "e74c13ec416581c95133c4c9b650ac9b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Touch Fallback Hotspot"
    password: "YX0PQXg6XQzA"

captive_portal:
    
# ===== Display =====
touchscreen:
  - platform: axs15231
    id: my_touch
    display: my_display
    i2c_id: touchscreen_bus
    calibration:
      x_min: 0
      x_max: 480
      y_min: 0
      y_max: 320
    transform:
      swap_xy: true
      mirror_y: true
    on_touch:
      - lambda: |-
          it.fill(Color(0, 0, 0));
          it.print(20, 40, id(font1), Color(255, 255, 255), "ESPHome OK");
          it.print(20, 80, id(font1), Color(0, 255, 0), "Display werkt");

# ===== Font =====
font:
  - file: "gfonts://Roboto"
    id: font1
    size: 24
