esphome:
  name: ili9341-hello

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  id: lcd
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

# Backlight (aan laten)
output:
  - platform: ledc
    pin: GPIO27
    id: backlight_pwm

light:
  - platform: monochromatic
    name: "Display Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON
    id: backlight

font:
  - file: "gfonts://Roboto"
    id: font_32
    size: 32



switch:
  - platform: template
    name: "Panel: Knop 1"
    id: panel_knop1
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      - lvgl.widget.update:
          id: my_button1
          state:
            checked: true

    on_turn_off:
      - lvgl.widget.update:
          id: my_button1
          state:
            checked: false

  - platform: template
    name: "Panel: Knop 2"
    id: panel_knop2
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_off:
      - lvgl.widget.update:
          id: my_button2
          state:
            checked: false

  - platform: template
    name: "Panel: Knop 3"
    id: panel_knop3
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      - lvgl.widget.update:
          id: my_button3
          state:
            checked: true

    on_turn_off:
      - lvgl.widget.update:
          id: my_button3
          state:
            checked: false

  - platform: template
    name: "Panel: Knop 4"
    id: panel_knop4
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      - lvgl.widget.update:
          id: my_button4
          state:
            checked: true

    on_turn_off:
      - lvgl.widget.update:
          id: my_button4
          state:
            checked: false

  - platform: template
    name: "Panel: Knop 5"
    id: panel_knop5
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      - lvgl.widget.update:
          id: my_button5
          state:
            checked: true

    on_turn_off:
      - lvgl.widget.update:
          id: my_button5
          state:
            checked: false

  - platform: template
    name: "Panel: Knop 6"
    id: panel_knop6
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      - lvgl.widget.update:
          id: my_button6
          state:
            checked: true

    on_turn_off:
      - lvgl.widget.update:
          id: my_button6
          state:
            checked: false



    



lvgl:

  displays:
    - tft

  touchscreens:
    - ts
  
  widgets:
#    - label:
#        align: CENTER
#        text: "Hello World!"

# Example slider with knob and indicator styling
    - slider:
      # main (background) styles
        bg_opa: cover
          
        radius: 0
        align: BOTTOM_MID
        width: 100%
        indicator:
          bg_opa: transp    # Makes the indicator part invisible
        knob:
          radius: 1
          width: 4
          height: 10%
          bg_color: 0x000000

    - button:
        id: my_button1
        text: "Button 1"
        checkable: true
        state:
          checked: true # here you activate the state to be used at boot
        checked:
          bg_color: 0x00FF00 # here you apply styles to be used when in the respective state
        align: LV_ALIGN_TOP_LEFT

        on_click:
          - switch.toggle: panel_knop1

        on_press:
          - lvgl.button.update:
              id: my_button1
              #text: "Released!"
              bg_color: 0x0000FF

        on_release:
          - lvgl.button.update:
              id: my_button1
              text: "Pressed!"
              bg_color: 0xFF0000

    - button:
        id: my_button2
        text: "Button 2"
        
        checkable: true
        state:
          checked: true # here you activate the state to be used at boot
        checked:
          bg_color: 0x00FF00 # here you apply styles to be used when in the respective state
        align: LV_ALIGN_TOP_MID

        on_click:
          - switch.toggle: panel_knop2

    - button:
        id: my_button3
        text: "Button 2"
        checkable: true
        state:
          checked: true # here you activate the state to be used at boot
        checked:
          bg_color: 0x00FF00 # here you apply styles to be used when in the respective state
        align: LV_ALIGN_TOP_RIGHT

        on_click:
          - switch.toggle: panel_knop3

    - button:
        id: my_button4
        text: "Button 4"
        checkable: true
        state:
          checked: true # here you activate the state to be used at boot
        checked:
          bg_color: 0x00FF00 # here you apply styles to be used when in the respective state
        align: LV_ALIGN_LEFT_MID

        on_click:
          - switch.toggle: panel_knop4

    - button:
        id: my_button5
        text: "Button 5"
        checkable: true
        state:
          checked: true # here you activate the state to be used at boot
        checked:
          bg_color: 0x00FF00 # here you apply styles to be used when in the respective state
        align: LV_ALIGN_CENTER

        on_click:
          - switch.toggle: panel_knop5

    - button:
        id: my_button6
        text: "Button 6"
        checkable: true
        state:
          checked: true # here you activate the state to be used at boot
        checked:
          bg_color: 0x00FF00 # here you apply styles to be used when in the respective state
        align: LV_ALIGN_RIGHT_MID

        on_click:
          - switch.toggle: panel_knop6



display:
  - platform: ili9xxx
    id: tft
    model: ili9341
    spi_id: lcd
    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO4

    #rotation: 90
    dimensions: 320x480
    color_palette: 8BIT
    color_order: bgr
    invert_colors: false
    update_interval: 1s
    show_test_card: false

touchscreen:
  - platform: xpt2046
    id: ts
    spi_id: lcd
    cs_pin: GPIO33
    update_interval: 50ms
    threshold: 700

    calibration:
      x_min: 418
      x_max: 3740
      y_min: 460
      y_max: 3581

    transform:
      mirror_x: true
      mirror_y: true
      swap_xy: false
