esphome:
  name: jc3248w535-hello-touch
  platformio_options:
    upload_speed: 921600
    board_build.flash_mode: dio
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
api: 
  encryption:
    key: Cvw+sqmt2lEAXasaoLyxYyr0NR3c9CFzsv4wjivQMpU=





ota:
  platform: esphome

wifi:
  use_address: 192.168.2.88
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# QSPI / Quad SPI bus voor het display
spi:
  - type: quad
    clk_pin: 47
    data_pins: [21, 48, 40, 39]

# I2C voor de AXS15231 touch controller
i2c:
  - sda: 4
    scl: 8

# Backlight (GPIO1)
output:
  - platform: ledc
    id: bl_pwm
    pin: 1

light:
  - platform: monochromatic
    id: backlight
    name: "Backlight"
    output: bl_pwm
    restore_mode: ALWAYS_ON

# Display driver
display:
  - platform: mipi_spi
    id: tft
    model: JC3248W535
    data_rate: 40MHz
    update_interval: never
    auto_clear_enabled: false

# Touchscreen
touchscreen:
  - platform: axs15231
    id: ts
    display: tft
    # interrupt_pin: <optioneel>
    # reset_pin: <optioneel>
    on_touch:
      - lambda: |-
          ESP_LOGI("touch", "x=%d y=%d raw_x=%d raw_y=%d",
                   touch.x, touch.y, touch.x_raw, touch.y_raw);

            

switch:
  - platform: template
    name: "Panel: Knop 1"
    id: panel_knop1
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      - lvgl.widget.update:
          id: my_button1
          state:
            checked: true
          bg_color: red

    on_turn_off:
      - lvgl.widget.update:
          id: my_button1
          state:
            checked: false
          bg_color: green

# LVGL “Hello world”
lvgl:
  displays:
    - tft
  touchscreens:
    - ts
  widgets:
    - keyboard:
        id: my_kb
        align: BOTTOM_MID
        width: 320
        height: 120
        
    - label:
        align: CENTER
        text: "Hello world"

    - button:
        id: my_button1
        align: TOP_MID
        width: 200
        height: 80
        text: "Knop 1"
        on_click:
          then:
            - switch.toggle: panel_knop1
