esphome:
  name: jc3248w535

esp32:
  board: esp32s3box
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf

external_components:
  - source: github://ageurtse/esphome-components
    components: [ axs15231 ]

logger:
api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#psram:
#  mode: octal
#speed: 120MHz

output:
  - platform: ledc
    pin:
      number: GPIO01
    id: lcdbacklight

light:
  - platform: monochromatic
    output: lcdbacklight
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON


# Backlight (aan laten)
# output:
#   - platform: ledc
#     pin: GPIO27
#     id: backlight_pwm

# light:
#   - platform: monochromatic
#     name: "TFT Backlight"
#     output: backlight_pwm
#     restore_mode: ALWAYS_ON

font:
  - file: "gfonts://Roboto"
    id: font_32
    size: 32

spi:
  id: display_qspi
  type: quad
  clk_pin: 47
  data_pins: [21,48,40,39]

i2c:
  sda: 4
  scl: 8
  id: touchscreen_bus
  frequency: 800khz


display:
  - platform: qspi_dbi
    model: CUSTOM
    data_rate: 40MHz
    dimensions:
      height: 480
      width: 320
    transform:
      mirror_x: false
      mirror_y: false
    cs_pin:
      number: 45
      ignore_strapping_warning: true
    auto_clear_enabled: false
    update_interval: never
    draw_from_origin: true
    rotation: 270
    init_sequence:
    lambda: |-
      it.fill(Color(0, 0, 0));
      it.print(20, 20, id(font_32), Color(255, 255, 255), "Hello world");

# touchscreen:
#   - platform: xpt2046
#     id: ts
#     spi_id: lcd
#     cs_pin: GPIO33
#     update_interval: 50ms
#     threshold: 700

#     calibration:
#       x_min: 418
#       x_max: 3740
#       y_min: 460
#       y_max: 3581

#     transform:
#       mirror_x: true
#       mirror_y: true
#       swap_xy: false
