esphome:
  name: ili9341-test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

output:
  - platform: ledc
    pin: GPIO27
    id: backlight_pwm

light:
  - platform: monochromatic
    name: "ILI9341 Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    model: ili9341
    cs_pin: GPIO15
    dc_pin: GPIO2
    # reset_pin: (bewust weggelaten; docs zeggen -1)
    color_palette: 8BIT
    color_order: bgr
    update_interval: 1s
    show_test_card: true
    invert_colors: false                                                                                                             
