esphome:
  name: ili9341-test
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: backlight
          brightness: 100%
          transition_length: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
spi:
  id: lcd
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

globals:
  - id: last_x
    type: int
    initial_value: "-1"
  - id: last_y
    type: int
    initial_value: "-1"
  - id: touching
    type: bool
    initial_value: "false"

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 24

text_sensor:
  - platform: homeassistant
    id: ha_test
    entity_id: sun.sun

display:
  - platform: ili9xxx
    id: tft
    model: ili9341
    spi_id: lcd
    cs_pin: GPIO15
    dc_pin: GPIO2
    # RST is -1 on this board (reset via ESP32 EN/reset); keep reset_pin unset

    color_palette: 8BIT
    color_order: bgr
    invert_colors: false

    rotation: 90
    dimensions: 320x240

    # begin stabiel; als dit goed is kun je later omhoog
    data_rate: 40000000   # 40 MHz
    update_interval: 33ms
    show_test_card: false

    lambda: |-
      it.fill(Color(0, 0, 0));

      // Home Assistant test: toon 1 entity-state
      it.printf(10, 10, id(font1), Color(255, 255, 255), "sun.sun: %s", id(ha_test).state.c_str());

      // center marker
      it.filled_circle(it.get_width()/2, it.get_height()/2, 2, Color(0, 80, 255));

      if (id(touching) && id(last_x) >= 0 && id(last_y) >= 0) {
        it.filled_circle(id(last_x), id(last_y), 10, Color(255,255,255));
        it.filled_circle(id(last_x), id(last_y), 7,  Color(255,0,0));
        it.filled_circle(id(last_x), id(last_y), 2,  Color(0,0,0));
      }

touchscreen:
  - platform: xpt2046
    id: ts
    spi_id: lcd
    cs_pin: GPIO33
    update_interval: 33ms
    threshold: 400
    calibration:
      x_min: 418
      x_max: 3740
      y_min: 460
      y_max: 3581
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: false

    on_touch:
      - lambda: |-
          const int x = (int)touch.x;
          const int y = (int)touch.y;

          id(touching) = true;

          // simpele smoothing
          if (id(last_x) < 0 || id(last_y) < 0) {
            id(last_x) = x;
            id(last_y) = y;
          } else {
            if (abs(x - id(last_x)) < 3 && abs(y - id(last_y)) < 3) return;
            id(last_x) = (id(last_x) * 3 + x) / 4;
            id(last_y) = (id(last_y) * 3 + y) / 4;
          }

          ESP_LOGI("touch", "x=%d y=%d raw_x=%d raw_y=%d",
                   id(last_x), id(last_y),
                   (int)touch.x_raw, (int)touch.y_raw);
      - component.update: tft

    on_release:
      - lambda: |-
          id(touching) = false;
          id(last_x) = -1;
          id(last_y) = -1;
      - component.update: tft

output:
  - platform: ledc
    id: backlight_pwm
    pin: GPIO27
    frequency: 1000Hz

light:
  - platform: monochromatic
    id: backlight
    name: "Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON
