esphome:
  name: ili9341-test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  id: tft_spi
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

output:
  - platform: ledc
    pin: GPIO27
    id: backlight_pwm

light:
  - platform: monochromatic
    name: "ILI9341 Backlight"
    output: backlight_pwm
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    id: tft
    model: ili9341
    spi_id: tft_spi
    cs_pin: GPIO15
    dc_pin: GPIO2
    color_palette: 8BIT
    color_order: bgr
    update_interval: 33ms
    show_test_card: false
    invert_colors: false
    rotation: 90
    data_rate: 5MHz
    lambda: |-
      it.fill(Color(0, 0, 0));  // zwart

      if (id(last_x) >= 0 && id(last_y) >= 0) {
        it.filled_circle(id(last_x), id(last_y), 6, Color(255, 255, 255)); // wit
      }

# touchscreen:
#   - platform: xpt2046
#     id: ts
#     spi_id: tft_spi
#     cs_pin: GPIO33
#     update_interval: 50ms
#     threshold: 700
#     calibration:
#       x_min: 418
#       x_max: 3740
#       y_min: 460
#       y_max: 3581
#     transform:
#       mirror_x: true
#       mirror_y: false
#       swap_xy: false
#     on_touch:
#       - lambda: |-
#           const int x = (int)touch.x;
#           const int y = (int)touch.y;
#
#           // eerste sample
#           if (id(last_x) < 0 || id(last_y) < 0) {
#             id(last_x) = x;
#             id(last_y) = y;
#           } else {
#             // deadband: negeer mini-jitter
#             if (abs(x - id(last_x)) < 3 && abs(y - id(last_y)) < 3) {
#               return;
#             }
#             // low-pass filter (EMA)
#             id(last_x) = (id(last_x) * 3 + x) / 4;
#             id(last_y) = (id(last_y) * 3 + y) / 4;
#           }
#
#           ESP_LOGI("touch", "x=%d y=%d raw_x=%d raw_y=%d",
#                    id(last_x), id(last_y),
#                    (int)touch.x_raw, (int)touch.y_raw);
#       - component.update: tft
#     on_release:
#       - lambda: |-
#           id(last_x) = -1;
#           id(last_y) = -1;
#       - component.update: tft


globals:
  - id: last_x
    type: int
    initial_value: "-1"
  - id: last_y
    type: int
    initial_value: "-1"
