esphome:
  name: my-led-project
  on_boot:
    priority: -100
    then:
      - light.turn_on:
          id: leds
          brightness: 75%
          red: 0%
          green: 100%
          blue: 0%

light:
  - platform: esp32_rmt_led_strip
    id: leds
    name: "LEDs"
    pin: GPIO21
    num_leds: 2
    rgb_order: GRB
    chipset: WS2812
esp32:
  board: esp32dev

wifi:
  ssid: "Cogito-Ergo-Sum"
  password: "bart-LETICIA-kyra"
  fast_connect: true
  power_save_mode: none

  ap:
    ssid: "My LED Project Fallback"
    password: "12345678"
    
logger:

api:

ota:
  - platform: esphome

